// Generated by CoffeeScript 1.12.7
(function() {
  'use strict';
  var $document, $window, _bpush, _cse, element, gcse_cx, i, isDebug, isSP, isSupportPushNotification, j, len, len1, ref, ref1, ref2, searchButton, setup_element;

  $window = window;

  $document = $window.document;

  isDebug = $window.location.hostname === 'localhost' || (typeof PRODUCTION === "undefined" || PRODUCTION === null);

  isSupportPushNotification = 'undefined' !== typeof Promise && 'undefined' !== typeof Notification && 'serviceWorker' in navigator ? !0 : !1;

  isSP = !$window.matchMedia("(min-width: 768px)").matches;

  window._loadScript = (function(d, src, reload) {
    var e, id, loaded;
    id = src;
    loaded = d.getElementById(id);
    if (loaded !== null) {
      if (!reload) {
        return;
      }
      loaded.parentNode.removeChild(loaded);
    }
    e = d.createElement('script');
    e.id = id;
    e.src = src;
    e.async = true;
    (d.getElementsByTagName('head')[0] || d.getElementsByTagName('body')[0]).appendChild(e);
  }).bind(null, $document);

  _bpush = $window._bpush || function() {
    return _loadScript('/bpush_loader.js', true);
  };

  element = $document.getElementById('bpush');

  if (element != null) {
    element.addEventListener('click', _bpush, false);
    if (!isSupportPushNotification) {
      element.classList.add('hidden');
    }
  }

  $window.addEventListener('load', function() {
    var outputElement, ref;
    outputElement = $document.getElementById('output');
    if ((ref = navigator.serviceWorker) != null) {
      ref.register('/service-worker.js', {
        scope: './'
      }).then(function(r) {})["catch"](function(whut) {
        console.error(whut);
      });
    }
    $window.addEventListener('beforeinstallprompt', function(e) {
      outputElement.textContent = 'beforeinstallprompt Event fired';
    });
  });

  ref = $document.querySelectorAll(isSP ? '.visible-xs-block' : '.hidden-xs' + ' .adsbygoogle');
  for (i = 0, len = ref.length; i < len; i++) {
    element = ref[i];
    element.parentNode.removeChild(element);
  }

  setup_element = function(element) {
    element.style.position = 'fixed';
    element.style.bottom = 0;
    element.style.zIndex = 3;
  };

  ref1 = $document.querySelectorAll('footer.bar-bottom');
  for (j = 0, len1 = ref1.length; j < len1; j++) {
    element = ref1[j];
    if (element.querySelector('iframe')) {
      setup_element(element);
      break;
    }
    element.addEventListener('DOMNodeInserted', function(event) {
      element = event.currentTarget;
      element.removeEventListener('DOMNodeInserted', arguments.callee, false);
      setup_element(element);
    }, false);
  }

  if ((ref2 = $document.getElementById('this-year')) != null) {
    ref2.textContent = new Date().getFullYear();
  }

  element = $document.getElementById('gcse-search');

  if (element != null) {
    gcse_cx = element.dataset.gcse_cx;
    element.parentNode.replaceChild($document.createElement('gcse:search'), element);
    setTimeout(function() {
      _loadScript("//cse.google.com/cse.js?cx=" + gcse_cx);
    }, 6000);
    _cse = $window._cse || function() {
      var gsc;
      cse.q.blur();
      gsc = $document.getElementById('gsc-i-id1');
      if (gsc === null) {
        return true;
      }
      gsc.value = cse.q.value;
      $document.querySelector('input.gsc-search-button').click();
      cse.reset();
      return false;
    };
    searchButton = $document.getElementById('search-button');
    if (searchButton != null) {
      searchButton.addEventListener('click', function(event) {
        return _cse();
      });
    }
  }

}).call(this);
